### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jawlen** [IlliumIv/Random-Features#4]
Im getting this error when it loads 

https://ibb.co/W2D2PFk

**Comment by IlliumIv** [comment]
Looks like your ExileApi outdated.

**Comment by Avadonia** [comment]
Look like i have the same issue with the latest (12 sept) update of exileapi any idea ? someone on https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/634782-poehud-plugin-random-features-12.html said you were referencing stuff on your own computer and that's why it didn't work, (and that the trial weren't working)

**Comment by IlliumIv** [comment]
@Avadonia
Hi.
Yea, your ExileApi outdated too. Latest commit is on Oct 25, 2019. You should build latest ExileApi version by himself or you can use my compiled: https://dropmefiles.com/GbJ0l . Archive can contain some trashing files, im too lazy and wont cleanup ExileApi directory before create archive. Compiled Random Features plugin already included.

Error on screen say about AtlasTexture type. This type was added Sep 17:
![изображение](https://user-images.githubusercontent.com/43261017/69452250-07be2480-0d83-11ea-9656-4aacdf8a6c11.png).
